name: flareline
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.5+5

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.1.1
  popover: ^0.2.9

  syncfusion_flutter_calendar: ^30.2.7
  syncfusion_flutter_charts: ^30.2.7
  syncfusion_flutter_core: ^30.2.7
  syncfusion_flutter_datagrid: ^30.2.7
  syncfusion_flutter_datepicker: ^30.2.7
  syncfusion_flutter_maps: ^30.2.7

  transparent_image: ^2.0.1
  google_fonts: any
  flutter_svg: ^2.1.1
  calendar_date_picker2: ^1.1.9
  file_picker: ^10.3.2
  hexcolor: ^3.0.1
  responsive_builder: ^0.7.1
  window_manager: ^0.3.9
  intl: ^0.20.0
  avatar_glow: ^3.0.1
  json_annotation: any
  image_picker: ^1.1.2
  mime: ^2.0.0
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  logger: ^2.2.0
  url_launcher: ^6.2.6
  path: ^1.9.0
  toastification: ^2.3.0
  iconsax_flutter: ^1.0.0
  quickalert: ^1.1.0
  rflutter_alert: ^2.0.7
  flutter_colorpicker: ^1.1.0
  multi_select_flutter: ^4.1.3
  flex_color_scheme: ^8.0.0

  flareline_uikit:
    path: FlareLine-UiKit

dependency_overrides:
  web: ^1.1.1
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/brand/
    - assets/cards/
    - assets/country/
    - assets/cover/
    - assets/icon/
    - assets/logo/
    - assets/product/
    - assets/task/
    - assets/user/
    - assets/signin/
    - assets/alert/
    - assets/toolbar/
    - assets/sidebar/
    - assets/australia.json
    - assets/routes/
    - assets/api/
    - assets/ai/
    - assets/crm/
